version = 1

[[annotations]]
path = [
    "repolinter.json",
    "NOTICE",
    ".github/CODEOWNERS",
    ".github/dependabot.yml",
]
SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    ".github/inditextech-ci-go.json",
    ".github/inditextech-ci-sync-manifest.json",
    ".sync-exclude",
    "code/.gitignore",
    "code/.tool-versions",
    "code/Makefile",
    "code/go.mod"
]
SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"
